name: Mirror to GitLab

on:
  push:
    branches:
      - dev   # trigger only when pushing to dev branch

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Push to GitLab
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/juakazike/gender-sensitization-engine.git
          git push gitlab dev --force
